### ISSUE TITLE
Re-build image on new mod versions

### ISSUE THREAD

**Issue by adn77** [Icinga/docker-icingaweb2#122]
I use icinga/icingaweb2 as base for our install.

Unfortunately the image only gets build when there is a new icingaweb release. As the release of icingaweb is not increased when major plugins are updated (e.g. icingadbweb) I end up manually bind-mounting more current plugin releases into the container.

There is the **main** tag which appears to be build daily, but I didn't find any CI chain for this.

Is there any chance of building the icingaweb2 image more often or even linking the github actions once an included plugin gets updated?

**Comment by oxzi** [comment]
> Unfortunately the image only gets build when there is a new icingaweb release. As the release of icingaweb is not increased when major plugins are updated (e.g. icingadbweb) I end up manually bind-mounting more current plugin releases into the container.

As [`get-mods.sh`](https://github.com/Icinga/docker-icingaweb2/blob/master/get-mods.sh) is part of the [Dockerfile's build](https://github.com/Icinga/docker-icingaweb2/blob/60579f5c9daacd3fe2d07ea6648c7dff35cd13aa/Dockerfile#L11-L25) and not of the entrypoint, the modules won't get bumped.
This is, as you rightly point out, a problem with outdated modules.

> There is the **main** tag which appears to be build daily, but I didn't find any CI chain for this.

This repository here is used as a GitHub Action within icingaweb2: <https://github.com/Icinga/icingaweb2/blob/main/.github/workflows/docker.yml>

One easy fix would be to include a GitHub Action Job similar to those in icingaweb2 for `github.event_name == 'release'` to each module listed in `get-mods.sh`. _Edit:_ The cron job/Action from icingaweb2 could also rebuild the latest tag on a daily basis.

**Comment by Al2Klimov** [comment]
> There is the **main** tag which appears to be build daily

Indeed, no, it's built regularly, but not daily: https://hub.docker.com/layers/icinga/icingaweb2/main/images/sha256-03239e2b34c6674a3aa18767a48e25d7c73a0a56e5b54feaa57a0035bd3d0248?context=explore

**Comment by Al2Klimov** [comment]
> The cron job/Action from icingaweb2 could also rebuild the latest tag

Good idea! IMAO we should let this happen weekly. People on the latest tag expect and want the _latest_ stuff. In case of breaking changes in mods users even have multiple options:

* Rollback
* Temporarily mount older mod version

CC @lippserd

**Comment by adn77** [comment]
I'd be interested in testing your new ini-parsing PR in a :latest tag as well 🙂

**Comment by Al2Klimov** [comment]
# TODO

* [ ] Await next Icinga-K8s release, see how well its Docker GHA work
* [ ] Based on that, maybe alter our image build process
* [ ] Once the latter is clear, base a new GHA on it, which runs on every mod release

**Comment by jan-kantert** [comment]
We also would like a new release with the latest icingadb(-web) version :-).

**Comment by lersveen** [comment]
Hey! As upgrading to Icinga 2.15.0 requires Icinga DB 1.4.0 and Icinga DB Web 1.2.0, the lack of an updated (stable) icingaweb2 image with Icinga DB Web 1.2.0 now prevents us from upgrading. Any plans to fix?

**Comment by lippserd** [comment]
> Hey! As upgrading to Icinga 2.15.0 requires Icinga DB 1.4.0 and Icinga DB Web 1.2.0, the lack of an updated (stable) icingaweb2 image with Icinga DB Web 1.2.0 now prevents us from upgrading. Any plans to fix?

New image has been uploaded.

**Comment by adn77** [comment]
There's again an updated Icinga DB Web v1.2.3 - a new icingaweb2 image would be great.

Also, since lots of issues deal with improper ini-file creation from environment vars, could you please give https://github.com/Icinga/docker-icingaweb2/pull/123 a chance?!
